// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getTenantSlug } from '@/lib/tenant';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// O slug do cliente (subdomínio) vai em todo request no header `x-org-slug`.
// O RLS (current_org_id / current_papel) usa esse header para escopar os dados
// à org ativa e validar a membership do usuário. Constante por origem (subdomínio).
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { 'x-org-slug': getTenantSlug() },
  },
});